// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/parcello.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:
	v1/parcello.proto

It has these top-level messages:
	DeliverRequest
	DeliverResponse
	Envelope
	Timestamp
*/
package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeliverRequest struct {
	Envelope *Envelope `protobuf:"bytes,1,opt,name=envelope" json:"envelope,omitempty"`
}

func (m *DeliverRequest) Reset()                    { *m = DeliverRequest{} }
func (m *DeliverRequest) String() string            { return proto.CompactTextString(m) }
func (*DeliverRequest) ProtoMessage()               {}
func (*DeliverRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeliverRequest) GetEnvelope() *Envelope {
	if m != nil {
		return m.Envelope
	}
	return nil
}

type DeliverResponse struct {
	EnqueueTime  *Timestamp `protobuf:"bytes,1,opt,name=enqueueTime" json:"enqueueTime,omitempty"`
	ErrorMessage string     `protobuf:"bytes,2,opt,name=errorMessage" json:"errorMessage,omitempty"`
}

func (m *DeliverResponse) Reset()                    { *m = DeliverResponse{} }
func (m *DeliverResponse) String() string            { return proto.CompactTextString(m) }
func (*DeliverResponse) ProtoMessage()               {}
func (*DeliverResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DeliverResponse) GetEnqueueTime() *Timestamp {
	if m != nil {
		return m.EnqueueTime
	}
	return nil
}

func (m *DeliverResponse) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

type Envelope struct {
	// fixed data
	Payload          []byte            `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Attributes       map[string]string `protobuf:"bytes,2,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	DestinationTopic string            `protobuf:"bytes,3,opt,name=destinationTopic" json:"destinationTopic,omitempty"`
	UndeliveredTopic string            `protobuf:"bytes,4,opt,name=undeliveredTopic" json:"undeliveredTopic,omitempty"`
	PublishAfter     *Timestamp        `protobuf:"bytes,5,opt,name=publishAfter" json:"publishAfter,omitempty"`
	MaxRetries       uint32            `protobuf:"varint,6,opt,name=maxRetries" json:"maxRetries,omitempty"`
}

func (m *Envelope) Reset()                    { *m = Envelope{} }
func (m *Envelope) String() string            { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()               {}
func (*Envelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Envelope) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Envelope) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Envelope) GetDestinationTopic() string {
	if m != nil {
		return m.DestinationTopic
	}
	return ""
}

func (m *Envelope) GetUndeliveredTopic() string {
	if m != nil {
		return m.UndeliveredTopic
	}
	return ""
}

func (m *Envelope) GetPublishAfter() *Timestamp {
	if m != nil {
		return m.PublishAfter
	}
	return nil
}

func (m *Envelope) GetMaxRetries() uint32 {
	if m != nil {
		return m.MaxRetries
	}
	return 0
}

type Timestamp struct {
	Seconds uint64 `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Timestamp) GetSeconds() uint64 {
	if m != nil {
		return m.Seconds
	}
	return 0
}

func init() {
	proto.RegisterType((*DeliverRequest)(nil), "v1.DeliverRequest")
	proto.RegisterType((*DeliverResponse)(nil), "v1.DeliverResponse")
	proto.RegisterType((*Envelope)(nil), "v1.Envelope")
	proto.RegisterType((*Timestamp)(nil), "v1.Timestamp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DeliveryService service

type DeliveryServiceClient interface {
	Deliver(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error)
}

type deliveryServiceClient struct {
	cc *grpc.ClientConn
}

func NewDeliveryServiceClient(cc *grpc.ClientConn) DeliveryServiceClient {
	return &deliveryServiceClient{cc}
}

func (c *deliveryServiceClient) Deliver(ctx context.Context, in *DeliverRequest, opts ...grpc.CallOption) (*DeliverResponse, error) {
	out := new(DeliverResponse)
	err := grpc.Invoke(ctx, "/v1.DeliveryService/Deliver", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DeliveryService service

type DeliveryServiceServer interface {
	Deliver(context.Context, *DeliverRequest) (*DeliverResponse, error)
}

func RegisterDeliveryServiceServer(s *grpc.Server, srv DeliveryServiceServer) {
	s.RegisterService(&_DeliveryService_serviceDesc, srv)
}

func _DeliveryService_Deliver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeliveryServiceServer).Deliver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.DeliveryService/Deliver",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeliveryServiceServer).Deliver(ctx, req.(*DeliverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DeliveryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.DeliveryService",
	HandlerType: (*DeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Deliver",
			Handler:    _DeliveryService_Deliver_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/parcello.proto",
}

func init() { proto.RegisterFile("v1/parcello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x6f, 0xd4, 0x30,
	0x14, 0x54, 0xb2, 0xfd, 0xda, 0xb7, 0x5b, 0x5a, 0x0c, 0x87, 0xa8, 0x42, 0xb0, 0x44, 0x42, 0x8a,
	0x38, 0x64, 0x95, 0xe5, 0x82, 0x2a, 0x38, 0x14, 0xb1, 0x47, 0x2e, 0xa6, 0x27, 0x6e, 0xde, 0xe4,
	0xb5, 0xb5, 0xea, 0xd8, 0xae, 0xbf, 0xc4, 0xfe, 0x47, 0x7e, 0x14, 0x4a, 0xd2, 0x44, 0xc9, 0xc2,
	0x2d, 0x33, 0x9e, 0x89, 0xdf, 0x1b, 0x0f, 0xbc, 0x0c, 0xc5, 0x5a, 0x33, 0x53, 0xa2, 0x10, 0x2a,
	0xd7, 0x46, 0x39, 0x45, 0xe2, 0x50, 0xa4, 0xd7, 0xf0, 0xe2, 0x3b, 0x0a, 0x1e, 0xd0, 0x50, 0x7c,
	0xf2, 0x68, 0x1d, 0xc9, 0xe0, 0x0c, 0x65, 0x40, 0xa1, 0x34, 0x26, 0xd1, 0x2a, 0xca, 0x16, 0x9b,
	0x65, 0x1e, 0x8a, 0x7c, 0xfb, 0xcc, 0xd1, 0xe1, 0x34, 0xbd, 0x83, 0x8b, 0xc1, 0x6b, 0xb5, 0x92,
	0x16, 0xc9, 0x1a, 0x16, 0x28, 0x9f, 0x3c, 0x7a, 0xbc, 0xe5, 0x75, 0xef, 0x3f, 0x6f, 0xfc, 0x0d,
	0xb6, 0x8e, 0xd5, 0x9a, 0x8e, 0x15, 0x24, 0x85, 0x25, 0x1a, 0xa3, 0xcc, 0x0f, 0xb4, 0x96, 0xdd,
	0x63, 0x12, 0xaf, 0xa2, 0x6c, 0x4e, 0x27, 0x5c, 0xfa, 0x27, 0x86, 0xb3, 0xfe, 0x7a, 0x92, 0xc0,
	0xa9, 0x66, 0x7b, 0xa1, 0x58, 0xd5, 0xfe, 0x7d, 0x49, 0x7b, 0x48, 0xbe, 0x00, 0x30, 0xe7, 0x0c,
	0xdf, 0x79, 0x87, 0x36, 0x89, 0x57, 0xb3, 0x6c, 0xb1, 0x79, 0x33, 0x1e, 0x3d, 0xbf, 0x19, 0x8e,
	0xb7, 0xd2, 0x99, 0x3d, 0x1d, 0xe9, 0xc9, 0x47, 0xb8, 0xac, 0xd0, 0x3a, 0x2e, 0x99, 0xe3, 0x4a,
	0xde, 0x2a, 0xcd, 0xcb, 0x64, 0xd6, 0x0e, 0xf3, 0x0f, 0xdf, 0x68, 0xbd, 0xac, 0xba, 0xd5, 0xb1,
	0xea, 0xb4, 0x47, 0x9d, 0xf6, 0x90, 0x27, 0x05, 0x2c, 0xb5, 0xdf, 0x09, 0x6e, 0x1f, 0x6e, 0xee,
	0x1c, 0x9a, 0xe4, 0xf8, 0x7f, 0x91, 0x4c, 0x24, 0xe4, 0x2d, 0x40, 0xcd, 0x7e, 0x53, 0x74, 0x86,
	0xa3, 0x4d, 0x4e, 0x56, 0x51, 0x76, 0x4e, 0x47, 0xcc, 0xd5, 0x57, 0xb8, 0x38, 0xd8, 0x84, 0x5c,
	0xc2, 0xec, 0x11, 0xf7, 0x6d, 0x22, 0x73, 0xda, 0x7c, 0x92, 0xd7, 0x70, 0x1c, 0x98, 0xf0, 0x7d,
	0xa2, 0x1d, 0xb8, 0x8e, 0x3f, 0x47, 0xe9, 0x07, 0x98, 0x0f, 0x37, 0x37, 0x71, 0x5a, 0x2c, 0x95,
	0xac, 0x6c, 0x6b, 0x3e, 0xa2, 0x3d, 0xdc, 0x6c, 0x87, 0xd7, 0xdd, 0xff, 0x44, 0x13, 0x78, 0x89,
	0x64, 0x03, 0xa7, 0xcf, 0x14, 0x21, 0xcd, 0x02, 0xd3, 0xe6, 0x5c, 0xbd, 0x9a, 0x70, 0x5d, 0x23,
	0xbe, 0xbd, 0xff, 0xf5, 0xee, 0x9e, 0xbb, 0x07, 0xbf, 0xcb, 0x4b, 0x55, 0xaf, 0xb1, 0xe6, 0xe5,
	0xa3, 0x40, 0x3e, 0x54, 0x71, 0x1d, 0x8a, 0xdd, 0x49, 0x5b, 0xc7, 0x4f, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0xcc, 0xfe, 0x42, 0x26, 0xa3, 0x02, 0x00, 0x00,
}
